### PR TITLE
Apply creator changes to other clients

### PR DESCRIPTION
**Pull request by tsegismont**
- [x] Oracle
- [x] MySQL
- [x] DB2
- [x] MSSQL

### CODE REVIEW

**Comment by geoand** [comment]
Thanks!

Let me know when this is ready so I can merge

**Comment by tsegismont** [comment]
@geoand it is ready

**Comment by geoand** [comment]
Thanks!!!

**Comment by tsegismont** [comment]
Thank *you* 🙂

**Pull request merged**
